[package]
name = "xrpl_types"
description = "Core types and related functions for the XRP Ledger"
version = "0.10.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gmosx/xrpl_sdk_rust/tree/main/xrpl_types"
keywords = ["xrpl", "ledger", "api"]
authors = ["George Moschovitis <gmosx@reizu.org>"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1.0.44"
bs58 = {version = "0.5.0", features = ["check"]}
ascii = "1.1.0"
hex = "0.4.3"
enumflags2 = { version = "0.7.7" }

[dev-dependencies]
assert_matches = "1.5.0"
hex = "0.4.3"